version: '3.8'

services:
  fastapi:
    image: fastapi-hello:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"  # expose FastAPI on host port 8000
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-server
    ports:
      - "8080:8080"  # Jenkins web UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home:
